#!/bin/bash
#
# Script to get a list of all aosp-mirror clone directories
git clone https://github.com/WestCoastRomS/android_hardware_broadcom_wlan.git
git clone https://github.com/WestCoastRomS/android_hardware_interfaces.git
git clone https://github.com/WestCoastRomS/android_hardware_nxp_nfc.git
git clone https://github.com/WestCoastRomS/android_hardware_qcom_audio.git
git clone https://github.com/WestCoastRomS/android_hardware_qcom_bootctrl.git
git clone https://github.com/WestCoastRomS/android_hardware_qcom_bt.git
git clone https://github.com/WestCoastRomS/android_hardware_qcom_camera.git
git clone https://github.com/WestCoastRomS/android_hardware_qcom_display.git
git clone https://github.com/WestCoastRomS/android_hardware_qcom_fm.git
git clone https://github.com/WestCoastRomS/android_hardware_qcom_gps.git
git clone https://github.com/WestCoastRomS/android_hardware_qcom_keymaster.git
git clone https://github.com/WestCoastRomS/android_hardware_qcom_media.git
git clone https://github.com/WestCoastRomS/android_hardware_qcom_msm8x84.git
git clone https://github.com/WestCoastRomS/android_hardware_qcom_sdm845_bt.git
git clone https://github.com/WestCoastRomS/android_hardware_qcom_sdm845_data_ipacfg-mgr.git
git clone https://github.com/WestCoastRomS/android_hardware_qcom_sdm845_display.git
git clone https://github.com/WestCoastRomS/android_hardware_qcom_sdm845_gps.git
git clone https://github.com/WestCoastRomS/android_hardware_qcom_sdm845_media.git
git clone https://github.com/WestCoastRomS/android-platform-art.git
git clone https://github.com/WestCoastRomS/android-platform-bionic.git
git clone https://github.com/WestCoastRomS/android_bionic.git
git clone https://github.com/WestCoastRomS/android_bootable_recovery.git
git clone https://github.com/WestCoastRomS/android_build.git
git clone https://github.com/WestCoastRomS/android_build_kati.git
git clone https://github.com/WestCoastRomS/android_build_soong.git
git clone https://github.com/WestCoastRomS/android_cpp.git
git clone https://github.com/WestCoastRomS/android_device_google_bonito.git
git clone https://github.com/WestCoastRomS/android_device_google_bonito-sepolicy.git
git clone https://github.com/WestCoastRomS/android_device_google_marlin.git
git clone https://github.com/WestCoastRomS/android_device_lineage_sepolicy.git
git clone https://github.com/WestCoastRomS/android_external_ant-wireless_antradio-library.git
git clone https://github.com/WestCoastRomS/android_external_ant-wireless_ant_native.git
git clone https://github.com/WestCoastRomS/android_external_ant-wireless_ant_service.git
git clone https://github.com/WestCoastRomS/android_external_bash.git
git clone https://github.com/WestCoastRomS/android_external_brctl.git
git clone https://github.com/WestCoastRomS/android_external_clang.git
git clone https://github.com/WestCoastRomS/android_external_connectivity.git
git clone https://github.com/WestCoastRomS/android_external_drm_hwcomposer.git
git clone https://github.com/WestCoastRomS/android_external_DUI.git
git clone https://github.com/WestCoastRomS/android_external_ebtables.git
git clone https://github.com/WestCoastRomS/android_external_exfat.git
git clone https://github.com/WestCoastRomS/android_external_expat.git
git clone https://github.com/WestCoastRomS/android_external_freetype.git
git clone https://github.com/WestCoastRomS/android_external_google.git
git clone https://github.com/WestCoastRomS/android_external_htop.git
git clone https://github.com/WestCoastRomS/android_external_jemalloc.git
git clone https://github.com/WestCoastRomS/android_external_json-c.git
git clone https://github.com/WestCoastRomS/android_external_libcups.git
git clone https://github.com/WestCoastRomS/android_external_libhevc.git
git clone https://github.com/WestCoastRomS/android_external_libjpeg-turbo.git
git clone https://github.com/WestCoastRomS/android_external_libncurses.git
git clone https://github.com/WestCoastRomS/android_external_libnfc-nxp.git
git clone https://github.com/WestCoastRomS/android_external_libpng.git
git clone https://github.com/WestCoastRomS/android_external_libtar.git
git clone https://github.com/WestCoastRomS/android_external_mksh.git
git clone https://github.com/WestCoastRomS/android_external_nano.git
git clone https://github.com/WestCoastRomS/android_external_ntfs-3g.git
git clone https://github.com/WestCoastRomS/android_external_openssh.git
git clone https://github.com/WestCoastRomS/android_external_p7zip.git
git clone https://github.com/WestCoastRomS/android_external_perfetto.git
git clone https://github.com/WestCoastRomS/android_external_pigz.git
git clone https://github.com/WestCoastRomS/android_external_powertop.git
git clone https://github.com/WestCoastRomS/android_external_protobuf.git
git clone https://github.com/WestCoastRomS/android_external_rsync.git
git clone https://github.com/WestCoastRomS/android_external_selinux.git
git clone https://github.com/WestCoastRomS/android_external_skia.git
git clone https://github.com/WestCoastRomS/android_external_sqlite.git
git clone https://github.com/WestCoastRomS/android_external_tinycompress.git
git clone https://github.com/WestCoastRomS/android_external_toybox.git
git clone https://github.com/WestCoastRomS/android_external_unrar.git
git clone https://github.com/WestCoastRomS/android_external_vim.git
git clone https://github.com/WestCoastRomS/android_external_zip.git
git clone https://github.com/WestCoastRomS/android_frameworks_av.git
git clone https://github.com/WestCoastRomS/android_frameworks_base.git
git clone https://github.com/WestCoastRomS/android_frameworks_compile_mclinker.git
git clone https://github.com/WestCoastRomS/android_frameworks_native.git
git clone https://github.com/WestCoastRomS/android_frameworks_opt_net_ims.git
git clone https://github.com/WestCoastRomS/android_frameworks_opt_net_wifi.git
git clone https://github.com/WestCoastRomS/android_frameworks_opt_telephony.git
git clone https://github.com/WestCoastRomS/android_frameworks_support.git
git clone https://github.com/WestCoastRomS/android_hardware_broadcom_libbt.git
git clone https://github.com/WestCoastRomS/android_hardware_broadcom_nfc.git


